services:
  - type: web
    name: calculadora-baterias
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api3:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
